# Numpy
  - NumPy is a multi-dimensional array library
  - it is faster than lists
  - it uses fixed type
  - it is faster to read as it uses less bytes of memory
  - no type checking when iterating through objects
  - numpy uses contiguous memory
    benefits
    - SIMD vector processing
    - Effective cache utilization

  - applications
    - mathematics (MATLAB replacement)
    - plotting (matplotlib)
    - backend (pandas, connect 4, digital photography)
    - machine learning

YT video: https://youtu.be/QUT1VHiLmmI?si=Ema9OrDFDxCCIswj

# Installing NumPy

In [277]:
pip install numpy

# Loading NumPy

In [278]:
import numpy as np
import sys

# Basics

1-D array

In [279]:
# 1-D array
a= np.array([1,2,3])
print(a)

[1 2 3]


2-D array

In [280]:
# 2-D array
b= np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


Get dimension

In [281]:
#get dimension
print(a.ndim)
print(b.ndim)

1
2


Getting shape

In [282]:
#get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


Getting type

In [283]:
#get type
print(a.dtype)
print(b.dtype)

int64
int64


Getting size

In [284]:
#get size
print(a.itemsize)
print(b.itemsize)

8
8


Total Size

In [285]:
# total size (a.size*a.itemsize)
print(a.nbytes)
print(b.nbytes)

24
48


Getting total no of elements

In [286]:
#get number of elements
print(a.size)
print(b.size)

3
6


# Accessing/changing specific elements, rows, columns, etc bold text

In [287]:
a = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])
print(a)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


Getting a specific element [row,column]

In [288]:
#get a specific element [r,c]
a[1,7]

18

Getting a specific row

In [289]:
#get a specific row
a[1,:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

Getting a specific colimn

In [290]:
#get a specific column
a[:,4]

array([ 5, 15])

Step size [start index: stop index: step size]

In [291]:
#Step size [start index: stop index: step size]
a[0,5:0:-2]

array([6, 4, 2])

changing an element

In [292]:
# changing an element
a[0,4] = 99
a[:,7] = [100,200]
print(a)

[[  1   2   3   4  99   6   7 100   9  10]
 [ 11  12  13  14  15  16  17 200  19  20]]


3-d example

In [293]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Getting a specific element (work outside in)

In [294]:
# Get specific element (work outside in)
a[0,1,1]

4

Replacing an element

In [295]:
#Replacing an element
a[:,0,:] = [[00,00],[99,99]]
print(a)

[[[ 0  0]
  [ 3  4]]

 [[99 99]
  [ 7  8]]]


# Initializing different types of arrays

Setting all zero matrix

In [297]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [298]:
# All 0s matrix
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [299]:
# All 0s matrix
np.zeros((2,3,4,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

Setting all one matrix

In [300]:
# All 1s matrix
np.ones((4,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [301]:
# All 1s matrix
np.ones((4,3,3), dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int32)

Setting all any number matrix

In [302]:
# Any other number
# ((rows,columns),element)
np.full((10,10),10)

array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [303]:
# Any other number (full_like)
np.full_like(a, 4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

Random decimal numbers

In [304]:
# Random decimal numbers
np.random.rand(4,2,2)

array([[[0.09157834, 0.85873687],
        [0.84830297, 0.13762574]],

       [[0.04281042, 0.43267205],
        [0.85846597, 0.77623118]],

       [[0.56111398, 0.20634772],
        [0.78991036, 0.25249753]],

       [[0.94000731, 0.60094387],
        [0.50231032, 0.59898403]]])

Random integer values

In [305]:
# Random Integer values
np.random.randint(-10,20, size=(3,3))

array([[-2,  2, -7],
       [ 3,  0, 15],
       [ 2, 16, -4]])

Identity Matrix

In [306]:
# The identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Repeating an array

In [307]:
# Repeat an array
arr = np.array([[1,2,3]])
a = np.repeat(arr,3, axis=0)
print(a)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [308]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 3
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 3. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 3. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Copying array

In [309]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


# Basic mathematics

In [310]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [311]:
a+1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [312]:
a-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [313]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [314]:
b = np.array([1,0,1,0,1,0,1,0,1,0])
a+b

array([ 2,  2,  4,  4,  6,  6,  8,  8, 10, 10])

In [315]:
a**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [316]:
a**3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [317]:
np.sin(a)
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153])

# Linear algrebra

Multiplying 2 matrices

In [318]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

#multiplying 2 matrices
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

Finding determinant

In [319]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

# Statisitics

In [320]:
stats = np.array([[1,2,3,4,5],[6,7,8,9,10]])
stats

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

Minimum Value

In [321]:
np.min(stats)

1

Minimum Value in specifc row

In [322]:
np.min(stats, axis=1)

array([1, 6])

Maximum Value

In [323]:
np.max(stats)

10

Maximum Value in specific row

In [324]:
np.max(stats, axis=1)

array([ 5, 10])

Sum of all the elements

In [325]:
np.sum(stats)

55

# Reorganizing arrays

Reshaping an array

In [326]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Vertically stacking vectors

In [327]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

Horizontally stacking vectors

In [328]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

Loading data from file

In [329]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


Boolean masking and advanced indexing

In [331]:
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [332]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [330]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])